[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
